services:
  db:
      image: mysql:8.0
      environment:
        MYSQL_ROOT_PASSWORD: analisis1-2025  # contraseña de root
        MYSQL_DATABASE: SubscriptionPlatform  # Crea la base de datos automáticamente
        TZ: America/Guatemala # Zona horaria
      ports:
        - "3306:3306"  # Mapea el puerto 3306 del contenedor al puerto 3306 de la máquina local
      volumes:
        - ./backend/DB/DBSubPlatm.sql:/docker-entrypoint-initdb.d/init.sql
